export const ENUM_FINANCIAL_SETTINGS_OPERATOR_TAB = {
	GENERAL: "general",
	PAYMENT_SETTINGS: "payment_settings",
	TAX_SETTINGS: "tax_settings",
	CURRENCY: "currency"
} as const;

export type ENUM_FINANCIAL_SETTINGS_OPERATOR_TAB_TYPE =
	(typeof ENUM_FINANCIAL_SETTINGS_OPERATOR_TAB)[keyof typeof ENUM_FINANCIAL_SETTINGS_OPERATOR_TAB];
