import type { BadgeVariant } from "@/shared/ui";

import {
	ENUM_SUPPLIER_PAYMENT_STATUS,
	type ENUM_SUPPLIER_PAYMENT_STATUS_TYPE
} from "../types";

export const SUPPLIER_PAYMENT_STATUS_LABELS: Record<
	ENUM_SUPPLIER_PAYMENT_STATUS_TYPE,
	string | string
> = {
	[ENUM_SUPPLIER_PAYMENT_STATUS.CONFIRMED]: "confirmed",
	[ENUM_SUPPLIER_PAYMENT_STATUS.RECORDED]: "recorded"
};

export const SUPPLIER_PAYMENT_STATUS_VARIANTS: Record<
	ENUM_SUPPLIER_PAYMENT_STATUS_TYPE,
	BadgeVariant
> = {
	[ENUM_SUPPLIER_PAYMENT_STATUS.CONFIRMED]: "green",
	[ENUM_SUPPLIER_PAYMENT_STATUS.RECORDED]: "yellow"
};
