import { ENUM_PATH, buildRoute } from "@/shared/config";

import { ENUM_SUPPLIER_TYPE, type ENUM_SUPPLIER_TYPE_TYPE } from "../types";

export const SUPPLIER_PRODUCT_EDIT_PATH_BY_TYPE = {
	[ENUM_SUPPLIER_TYPE.TRAIN]: ENUM_PATH.LIBRARY.SUPPLIER_TRAIN_PRODUCT,
	[ENUM_SUPPLIER_TYPE.FLIGHT]: ENUM_PATH.LIBRARY.SUPPLIER_FLIGHT_PRODUCT,
	[ENUM_SUPPLIER_TYPE.BUS]: ENUM_PATH.LIBRARY.SUPPLIER_BUS_PRODUCT,
	[ENUM_SUPPLIER_TYPE.TRANSFER]: ENUM_PATH.LIBRARY.SUPPLIER_TRANSFER_PRODUCT,
	[ENUM_SUPPLIER_TYPE.ACTIVITY]: ENUM_PATH.LIBRARY.SUPPLIER_ACTIVITY_PRODUCT,
	[ENUM_SUPPLIER_TYPE.HOTEL]: ENUM_PATH.LIBRARY.SUPPLIER_HOTEL_PRODUCT,
	[ENUM_SUPPLIER_TYPE.MUSEUM]: ENUM_PATH.LIBRARY.SUPPLIER_HOTEL_PRODUCT
} as const;

export const buildSupplierProductEditRoute = (
	typ: ENUM_SUPPLIER_TYPE_TYPE,
	params: { supplierId: string; productId: string }
) => {
	const path =
		SUPPLIER_PRODUCT_EDIT_PATH_BY_TYPE[
			typ as keyof typeof SUPPLIER_PRODUCT_EDIT_PATH_BY_TYPE
		];

	if (!path) return undefined;

	return buildRoute(path, params);
};
