export const ENUM_SUPPLIER_PAYMENT_STATUS = {
	RECORDED: "recorded",
	CONFIRMED: "confirmed"
} as const;

export type ENUM_SUPPLIER_PAYMENT_STATUS_TYPE =
	(typeof ENUM_SUPPLIER_PAYMENT_STATUS)[keyof typeof ENUM_SUPPLIER_PAYMENT_STATUS];
