export const ENUM_POOL_ERROR_CODE = {
	POOL_MEMBER_NOT_FOUND: "POOL_MEMBER_NOT_FOUND",
	POOL_LAST_MEMBER: "POOL_LAST_MEMBER",
	POOL_ECHO_MISMATCH: "POOL_ECHO_MISMATCH",
	POOL_SUPPLY_MOVE: "POOL_SUPPLY_MOVE",
	POOL_REQUIRED: "POOL_REQUIRED",
	POOL_TYP_MISMATCH: "POOL_TYP_MISMATCH",
	EVENT_OPTION_NOT_FOUND: "EVENT_OPTION_NOT_FOUND"
} as const;

export type ENUM_POOL_ERROR_CODE_TYPE =
	(typeof ENUM_POOL_ERROR_CODE)[keyof typeof ENUM_POOL_ERROR_CODE];

export const ENUM_EVENT_POOL_VARIANT = {
	TOUR: "tour",
	LIBRARY: "library"
} as const;

export type ENUM_EVENT_POOL_VARIANT_TYPE =
	(typeof ENUM_EVENT_POOL_VARIANT)[keyof typeof ENUM_EVENT_POOL_VARIANT];

export type TEventPoolUiProps = {
	poolVariant: ENUM_EVENT_POOL_VARIANT_TYPE;
	onPoolSelect: (supplyId: string | undefined) => void;
};
