export const ENUM_PUBLISH_ERROR_CODE = {
	SCHEDULE_REQUIRED: "SCHEDULE_REQUIRED"
} as const;

export type ENUM_PUBLISH_ERROR_CODE_TYPE =
	(typeof ENUM_PUBLISH_ERROR_CODE)[keyof typeof ENUM_PUBLISH_ERROR_CODE];
