export const ENUM_ACCOMMODATION_PRICING_INVOICING = {
	INDIVIDUAL: "individual",
	PART_OF_PACKAGE: "part_of_package"
} as const;

export type ENUM_ACCOMMODATION_PRICING_INVOICING_TYPE =
	(typeof ENUM_ACCOMMODATION_PRICING_INVOICING)[keyof typeof ENUM_ACCOMMODATION_PRICING_INVOICING];

export const ENUM_ACCOMMODATION_PRICING_TYPE = {
	FLAT_RATE: "flat_rate",
	PER_ROOM: "per_room",
	PER_PERSON: "per_person"
} as const;

export type ENUM_ACCOMMODATION_PRICING_TYPE_TYPE =
	(typeof ENUM_ACCOMMODATION_PRICING_TYPE)[keyof typeof ENUM_ACCOMMODATION_PRICING_TYPE];

export const ENUM_ACCOMMODATION_EXPENSE_TYP = {
	PER_ROOM: "per_room",
	PER_ROOM_CATEGORY: "per_room_category"
} as const;

export type ENUM_ACCOMMODATION_EXPENSE_TYP_TYPE =
	(typeof ENUM_ACCOMMODATION_EXPENSE_TYP)[keyof typeof ENUM_ACCOMMODATION_EXPENSE_TYP];

export const ENUM_ACCOMMODATION_MARKUP_TYP = {
	FIXED: "fixed",
	PERCENTAGE: "percentage"
} as const;

export type ENUM_ACCOMMODATION_MARKUP_TYP_TYPE =
	(typeof ENUM_ACCOMMODATION_MARKUP_TYP)[keyof typeof ENUM_ACCOMMODATION_MARKUP_TYP];

export const ENUM_ACCOMMODATION_PRICING_FIELD = {
	INVOICING: "invoicing",
	PRICING_TYPE: "pricing_type",
	PRICE_BASED_ON_CLASS: "price_based_on_class",
	ADD_MARGIN_SEPARATELY: "add_margin_separately",
	EXPENSES: "expenses",
	TOTAL_PRICE: "total_price",
	TAXES: "taxes",
	CURRENCY: "currency",
	PACKAGE_TYPE: "package_type"
} as const;

export type ENUM_ACCOMMODATION_PRICING_FIELD_TYPE =
	(typeof ENUM_ACCOMMODATION_PRICING_FIELD)[keyof typeof ENUM_ACCOMMODATION_PRICING_FIELD];

export const ENUM_ACCOMMODATION_PRICE_ROW_FIELD = {
	COST: "cost",
	FEES: "fees",
	CURRENCY: "currency",
	MARKUP: "markup"
} as const;

export type ENUM_ACCOMMODATION_PRICE_ROW_FIELD_TYPE =
	(typeof ENUM_ACCOMMODATION_PRICE_ROW_FIELD)[keyof typeof ENUM_ACCOMMODATION_PRICE_ROW_FIELD];

export const ENUM_ACCOMMODATION_CATEGORY_ROW_FIELD = {
	NAME: "name",
	COST: ENUM_ACCOMMODATION_PRICE_ROW_FIELD.COST,
	FEES: ENUM_ACCOMMODATION_PRICE_ROW_FIELD.FEES,
	CURRENCY: ENUM_ACCOMMODATION_PRICE_ROW_FIELD.CURRENCY,
	MARKUP: ENUM_ACCOMMODATION_PRICE_ROW_FIELD.MARKUP
} as const;

export type ENUM_ACCOMMODATION_CATEGORY_ROW_FIELD_TYPE =
	(typeof ENUM_ACCOMMODATION_CATEGORY_ROW_FIELD)[keyof typeof ENUM_ACCOMMODATION_CATEGORY_ROW_FIELD];

export const ENUM_ACCOMMODATION_PER_ROOM_EXPENSES_FIELD = {
	ROOMS: "rooms",
	CATEGORIES: "categories"
} as const;

export type ENUM_ACCOMMODATION_PER_ROOM_EXPENSES_FIELD_TYPE =
	(typeof ENUM_ACCOMMODATION_PER_ROOM_EXPENSES_FIELD)[keyof typeof ENUM_ACCOMMODATION_PER_ROOM_EXPENSES_FIELD];

export interface IAccommodationPriceRowMarkup {
	typ: ENUM_ACCOMMODATION_MARKUP_TYP_TYPE;
	value: string;
}

export interface IAccommodationPerRoomPriceRow {
	[ENUM_ACCOMMODATION_PRICE_ROW_FIELD.COST]: number | null;
	[ENUM_ACCOMMODATION_PRICE_ROW_FIELD.FEES]: number | null;
	[ENUM_ACCOMMODATION_PRICE_ROW_FIELD.CURRENCY]: string;
	[ENUM_ACCOMMODATION_PRICE_ROW_FIELD.MARKUP]: IAccommodationPriceRowMarkup | null;
}

export interface IAccommodationCategoryPriceRow
	extends IAccommodationPerRoomPriceRow {
	[ENUM_ACCOMMODATION_CATEGORY_ROW_FIELD.NAME]: string;
}

export interface IAccommodationPerRoomExpenses {
	typ: typeof ENUM_ACCOMMODATION_EXPENSE_TYP.PER_ROOM;
	[ENUM_ACCOMMODATION_PER_ROOM_EXPENSES_FIELD.ROOMS]: IAccommodationPerRoomPriceRow[];
}

export interface IAccommodationPerRoomByClassPriceRow {
	[ENUM_ACCOMMODATION_PER_ROOM_EXPENSES_FIELD.CATEGORIES]: IAccommodationCategoryPriceRow[];
}

export interface IAccommodationPerRoomCategoryExpenses {
	typ: typeof ENUM_ACCOMMODATION_EXPENSE_TYP.PER_ROOM_CATEGORY;
	[ENUM_ACCOMMODATION_PER_ROOM_EXPENSES_FIELD.ROOMS]: IAccommodationPerRoomByClassPriceRow[];
}
