import { createEnumMapper } from "@/shared/utils";

import {
	ENUM_SUPPLIER_TYPE,
	ENUM_SUPPLIER_TYPE_BACKEND,
	type ENUM_SUPPLIER_TYPE_BACKEND_TYPE,
	type ENUM_SUPPLIER_TYPE_TYPE
} from "../types";

const MAP_SUPPLIER_TYPE: Record<
	ENUM_SUPPLIER_TYPE_TYPE,
	ENUM_SUPPLIER_TYPE_BACKEND_TYPE
> = {
	[ENUM_SUPPLIER_TYPE.FLIGHT]: ENUM_SUPPLIER_TYPE_BACKEND.FLIGHT,
	[ENUM_SUPPLIER_TYPE.HOTEL]: ENUM_SUPPLIER_TYPE_BACKEND.HOTEL,
	[ENUM_SUPPLIER_TYPE.MUSEUM]: ENUM_SUPPLIER_TYPE_BACKEND.MUSEUM,
	[ENUM_SUPPLIER_TYPE.TRANSFER]: ENUM_SUPPLIER_TYPE_BACKEND.TRANSFER,
	[ENUM_SUPPLIER_TYPE.ACTIVITY]: ENUM_SUPPLIER_TYPE_BACKEND.ACTIVITY,
	[ENUM_SUPPLIER_TYPE.TRAIN]: ENUM_SUPPLIER_TYPE_BACKEND.TRAIN,
	[ENUM_SUPPLIER_TYPE.BUS]: ENUM_SUPPLIER_TYPE_BACKEND.BUS
};

export const supplierTypeConverter = createEnumMapper<
	ENUM_SUPPLIER_TYPE_TYPE,
	ENUM_SUPPLIER_TYPE_BACKEND_TYPE
>(MAP_SUPPLIER_TYPE);
