export const ENUM_COPY_EVENT_ERROR_CODE = {
	NOT_FOUND: "NOT_FOUND",
	ARCHIVED_TOUR: "ARCHIVED_TOUR",
	GUIDE_LANGUAGES: "GUIDE_LANGUAGES",
	BOOKING_NOT_PROCESSING: "BOOKING_NOT_PROCESSING",
	NO_PERMISSION: "NO_PERMISSION"
} as const;

export type ENUM_COPY_EVENT_ERROR_CODE_TYPE =
	(typeof ENUM_COPY_EVENT_ERROR_CODE)[keyof typeof ENUM_COPY_EVENT_ERROR_CODE];
