import { z } from "zod";

import {
	CARS_SCHEMA,
	ENUM_FORM_SECTION,
	GENERAL_INFO_SCHEMA,
	PRICING_SCHEMA
} from "@/entities/tour";

export const TRANSPORTATION_EDIT_SCHEMA = z.object({
	[ENUM_FORM_SECTION.GENERAL]: GENERAL_INFO_SCHEMA,
	[ENUM_FORM_SECTION.CARS]: CARS_SCHEMA,
	[ENUM_FORM_SECTION.PRICING]: PRICING_SCHEMA,
	[ENUM_FORM_SECTION.NAME]: z.string().optional(),
	[ENUM_FORM_SECTION.DAY]: z.number().optional(),
	[ENUM_FORM_SECTION.POSITION]: z.number().optional()
});
