export const ENUM_FLIGHT_TRANSPORT_TYPE = {
	FLY: "fly",
	TRAIN: "train",
	BUS: "bus"
} as const;

export type ENUM_FLIGHT_TRANSPORT_TYPE_TYPE =
	(typeof ENUM_FLIGHT_TRANSPORT_TYPE)[keyof typeof ENUM_FLIGHT_TRANSPORT_TYPE];

export const ENUM_FORM_FLIGHT = {
	AIRLINE_CODE: "airline_code",
	FLIGHT_NUMBER: "flight_number",
	DEPARTURE_AIRPORT_CODE: "departure_airport_code",
	ARRIVAL_AIRPORT_CODE: "arrival_airport_code",
	DEPARTURE_DATE: "departure_date",
	ARRIVAL_DATE: "arrival_date",
	DEPARTURE_TIME: "departure_time",
	DEPARTURE_TIMEZONE: "departure_timezone",
	ARRIVAL_TIME: "arrival_time",
	ARRIVAL_TIMEZONE: "arrival_timezone",
	DEPARTURE_TERMINAL: "departure_terminal",
	DEPARTURE_GATE: "departure_gate",
	ARRIVAL_TERMINAL: "arrival_terminal",
	ARRIVAL_GATE: "arrival_gate",
	DESCRIPTION: "description",
	TRANSPORT_TYPE: "transport_type",
	ROUTE: "route"
} as const;

export type ENUM_FORM_FLIGHT_TYPE =
	(typeof ENUM_FORM_FLIGHT)[keyof typeof ENUM_FORM_FLIGHT];

export const ENUM_FORM_TRAIN = {
	CARRIER: "carrier",
	TRAIN_NUMBER: "train_number",
	DEPARTURE_STATION: "departure_station",
	ARRIVAL_STATION: "arrival_station",
	DEPARTURE_DATE: ENUM_FORM_FLIGHT.DEPARTURE_DATE,
	ARRIVAL_DATE: ENUM_FORM_FLIGHT.ARRIVAL_DATE,
	DEPARTURE_TIME: ENUM_FORM_FLIGHT.DEPARTURE_TIME,
	ARRIVAL_TIME: ENUM_FORM_FLIGHT.ARRIVAL_TIME,
	DEPARTURE_TIMEZONE: ENUM_FORM_FLIGHT.DEPARTURE_TIMEZONE,
	ARRIVAL_TIMEZONE: ENUM_FORM_FLIGHT.ARRIVAL_TIMEZONE,
	TRANSPORT_TYPE: ENUM_FORM_FLIGHT.TRANSPORT_TYPE
} as const;

export type ENUM_FORM_TRAIN_TYPE =
	(typeof ENUM_FORM_TRAIN)[keyof typeof ENUM_FORM_TRAIN];

export const ENUM_FORM_BUS = {
	BUS_COMPANY: "bus_company",
	BUS_NUMBER: "bus_number",
	DEPARTURE_POINT: "departure_point",
	ARRIVAL_POINT: "arrival_point",
	DEPARTURE_DATE: ENUM_FORM_FLIGHT.DEPARTURE_DATE,
	ARRIVAL_DATE: ENUM_FORM_FLIGHT.ARRIVAL_DATE,
	DEPARTURE_TIME: ENUM_FORM_FLIGHT.DEPARTURE_TIME,
	ARRIVAL_TIME: ENUM_FORM_FLIGHT.ARRIVAL_TIME,
	DEPARTURE_TIMEZONE: ENUM_FORM_FLIGHT.DEPARTURE_TIMEZONE,
	ARRIVAL_TIMEZONE: ENUM_FORM_FLIGHT.ARRIVAL_TIMEZONE,
	TRANSPORT_TYPE: ENUM_FORM_FLIGHT.TRANSPORT_TYPE
} as const;

export type ENUM_FORM_BUS_TYPE =
	(typeof ENUM_FORM_BUS)[keyof typeof ENUM_FORM_BUS];
