export {
	BOOKING_ORDER_STATUS_LABELS as RECONCILIATION_STATUS_LABELS,
	BOOKING_ORDER_STATUS_VARIANTS as RECONCILIATION_STATUS_VARIANTS
} from "@/entities/booking/order/constants/order-status.config";
