import { createEnumMapper } from "@/shared/utils";

import {
	ENUM_EVENT,
	ENUM_EVENT_BACKEND,
	type ENUM_EVENT_BACKEND_TYPE,
	type ENUM_EVENT_TYPE
} from "../types";

const BACKEND_TYP_TO_EVENT_TYPE: Partial<
	Record<ENUM_EVENT_BACKEND_TYPE, ENUM_EVENT_TYPE>
> = {
	[ENUM_EVENT_BACKEND.FLIGHT]: ENUM_EVENT.FLIGHT,
	[ENUM_EVENT_BACKEND.TRAIN]: ENUM_EVENT.FLIGHT,
	[ENUM_EVENT_BACKEND.BUS]: ENUM_EVENT.FLIGHT
};

const MAP_EVENT_TYPE_TO_BACKEND: Partial<
	Record<ENUM_EVENT_TYPE, ENUM_EVENT_BACKEND_TYPE>
> = {
	[ENUM_EVENT.FLIGHT]: ENUM_EVENT_BACKEND.FLIGHT,
	[ENUM_EVENT.TRANSPORTATION]: ENUM_EVENT_BACKEND.TRANSFER,
	[ENUM_EVENT.ACCOMMODATION]: ENUM_EVENT_BACKEND.HOUSING,
	[ENUM_EVENT.ACTIVITY]: ENUM_EVENT_BACKEND.ACTIVITY,
	[ENUM_EVENT.INFO]: ENUM_EVENT_BACKEND.REF,
	[ENUM_EVENT.GUIDE]: ENUM_EVENT_BACKEND.GUIDE,
	[ENUM_EVENT.SUPPLEMENT]: ENUM_EVENT_BACKEND.SUPPLEMENTARY,
	[ENUM_EVENT.MULTIPLY_OPTION]: ENUM_EVENT_BACKEND.OPTIONS
};

export const eventTypeMapper = createEnumMapper<
	ENUM_EVENT_TYPE,
	ENUM_EVENT_BACKEND_TYPE
>(MAP_EVENT_TYPE_TO_BACKEND);

export const mapBackendTypToEventType = (
	typ: ENUM_EVENT_BACKEND_TYPE | null | undefined
): ENUM_EVENT_TYPE | undefined => {
	if (!typ) return undefined;
	return BACKEND_TYP_TO_EVENT_TYPE[typ] ?? eventTypeMapper.from(typ);
};
